/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BloodChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "donationCountPublic"
      | "getDonationCount"
      | "getMyDonationCount"
      | "getMyLastVolume"
      | "protocolId"
      | "recordDonation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DonationRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "donationCountPublic",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyDonationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyLastVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDonation",
    values: [
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "donationCountPublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyDonationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyLastVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDonation",
    data: BytesLike
  ): Result;
}

export namespace DonationRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    ipfsCid: string,
    date: BigNumberish,
    locationHash: BytesLike,
    hospitalHash: BytesLike,
    donationType: BigNumberish,
    volume: BigNumberish,
    encVolume: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    ipfsCid: string,
    date: bigint,
    locationHash: string,
    hospitalHash: string,
    donationType: bigint,
    volume: bigint,
    encVolume: string
  ];
  export interface OutputObject {
    user: string;
    ipfsCid: string;
    date: bigint;
    locationHash: string;
    hospitalHash: string;
    donationType: bigint;
    volume: bigint;
    encVolume: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BloodChain extends BaseContract {
  connect(runner?: ContractRunner | null): BloodChain;
  waitForDeployment(): Promise<this>;

  interface: BloodChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  donationCountPublic: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getDonationCount: TypedContractMethod<[user: AddressLike], [string], "view">;

  getMyDonationCount: TypedContractMethod<[], [string], "view">;

  getMyLastVolume: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordDonation: TypedContractMethod<
    [
      inputVolume: BytesLike,
      inputProof: BytesLike,
      ipfsCid: string,
      date: BigNumberish,
      locationHash: BytesLike,
      hospitalHash: BytesLike,
      donationType: BigNumberish,
      publicVolume: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "donationCountPublic"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDonationCount"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMyDonationCount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyLastVolume"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDonation"
  ): TypedContractMethod<
    [
      inputVolume: BytesLike,
      inputProof: BytesLike,
      ipfsCid: string,
      date: BigNumberish,
      locationHash: BytesLike,
      hospitalHash: BytesLike,
      donationType: BigNumberish,
      publicVolume: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DonationRecorded"
  ): TypedContractEvent<
    DonationRecordedEvent.InputTuple,
    DonationRecordedEvent.OutputTuple,
    DonationRecordedEvent.OutputObject
  >;

  filters: {
    "DonationRecorded(address,string,uint64,bytes32,bytes32,uint8,uint32,bytes32)": TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
    DonationRecorded: TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
  };
}
