/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as medalNftSol from "./MedalNFT.sol";
export type { medalNftSol };
export type { BloodChain } from "./BloodChain";
