/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBloodChain,
  IBloodChainInterface,
} from "../../../contracts/MedalNFT.sol/IBloodChain";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "donationCountPublic",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBloodChain__factory {
  static readonly abi = _abi;
  static createInterface(): IBloodChainInterface {
    return new Interface(_abi) as IBloodChainInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBloodChain {
    return new Contract(address, _abi, runner) as unknown as IBloodChain;
  }
}
