/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBloodChain__factory } from "./IBloodChain__factory";
export { MedalNFT__factory } from "./MedalNFT__factory";
